spring.application.name=Store

spring.datasource.url=jdbc:mysql://localhost:3306/myqldatabaserepaso
spring.datasource.username=alba2002
spring.datasource.password=secretpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

